Update deploy-to-aks.yml

diff --git a/azure-pipelines/deploy-to-aks.yml b/azure-pipelines/deploy-to-aks.yml
--- a/azure-pipelines/deploy-to-aks.yml
+++ b/azure-pipelines/deploy-to-aks.yml
@@ -6,9 +6,8 @@ pool:
 
 variables:
   - group: my-secrets  
-    allowAccess: true
   - name: azureSubscription
-    value: 'sconnection'   
+    value: 'my-connection'  # مقدار درست `Service Connection` را جایگزین کنید
   - name: terraformWorkingDirectory
     value: 'environments/dev/'
 
@@ -24,7 +23,7 @@ stages:
     - task: AzureCLI@2
       displayName: 'Login to Azure'
       inputs:
-        azureSubscription: $(azureSubscription)
+        connectedServiceNameARM: $(azureSubscription)
         scriptType: bash
         scriptLocation: inlineScript
         inlineScript: |
@@ -49,5 +48,10 @@ stages:
 
     - script: |
         cd $(terraformWorkingDirectory)
-        terraform apply -auto-approve tfplan || exit 1
+        if [ -f tfplan ]; then
+          terraform apply -auto-approve tfplan || exit 1
+        else
+          echo "Terraform plan file not found! Skipping apply step."
+          exit 1
+        fi
       displayName: 'Apply Terraform Changes'
